# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sfp9EAvgO25FxuBvqbKJSMXGpNrQnxaS
"""

import numpy as np
lis1=[[1,2,3],[1,2,3],[1,3,4]]                
lis2=[[2,3,4],[3,4,5],[4,5,6]]
ml=np.multiply(lis1,lis2)
print(ml)

lis1=[[1,2,3],[1,2,3],[1,3,4]]                
lis2=[[2,3,4],[3,4,5],[4,5,6]]

r =[c*x for x,y in zip(lis1,lis2) for c,x in zip(x,y)]
r

lis1=[[1,2,3],[1,2,3],[1,3,4]]                       
             
lis2=[[2,3,4],[3,4,5],[4,5,6]]

      
lis3=[]

for i,j in  zip(lis1,lis2):
    #lis3.append(i*j)
    lis3.append(i[0]*j[0])
    lis3.append(i[1]*j[1])
    lis3.append(i[2]*j[2])
lis3